### ISSUE TITLE
trying to dump this dream town but i think because it has 7 residents its not letting me 

### ISSUE THREAD

**Issue by animalcrossingman** [Ixaruz/Luna-Archive-of-Dreams#2]
could you please  try and see if it works for you?  [DA-4637-0987-4982]

**Comment by Ixaruz** [comment]
Hey, could you describe the issue you are having a bit further?

It's letting me dump it soo..
![Screenshot](https://user-images.githubusercontent.com/44379110/103448219-795ee680-4c96-11eb-9fc5-e654592bcc03.png)

here the link.
https://github.com/Ixaruz/Luna-Archive-of-Dreams/tree/master/1.6.0/%5BDA-4637-0987-4982%5D%20ACNH%20Kant

**Comment by animalcrossingman** [comment]
yeah sure when i try to load the save on JKSV it hangs and never replaces the save

**Comment by Ixaruz** [comment]
Did you check if your file structure is right?
If it looks like this: SDMC:/JKSV/Animal Crossing New Horizons/[DA-4637-0987-4982] ACNH Kant/24.12.2020 @ 08-44/ and you're trying to load "[DA-4637-0987-4982] ACNH Kant", that will definitely not work, because the save is actually in the sub folder.

Idk what else your issue could be, if I restore the save using JKSV it works fine 😔

**Comment by animalcrossingman** [comment]
yeah its deffo on my  end  the  save you posted worked  thanks for the help!
