### ISSUE TITLE
Dump request : DA-4141-8912-8992

### ISSUE THREAD

**Issue by lutinotmalin** [Ixaruz/Luna-Archive-of-Dreams#3]
Hey Ixaruz !

First, I wanted to thank you about your wonderful software. The ability to backup dream islands and share them to everyone is a real must.

Actually, I would love to have a backup of the very best dream island I've ever visited, Mialand, DA-4141-8912-8992, though I'm not very confident to do it myself, as I don't even know if my Linux computer is compatible with Luna.

Could you do it if you got time then release the dump here ? It would be awesome. That dream island is so good it deserves to be in the Luna Archive anyway. :+1: 

Thanks again for your fantastic work. Can't wait to explore once again Mialand.

lutinotmalin

**Comment by Ixaruz** [comment]
Heyo,
 yeah unfortunately my HorizonCrypt release is Windows only. since its based on NHSE, which is based on .NET framework, it won't compile/run on Linux as far as I know - so you're pretty much out of luck :( sorry.
 
 anyway, I dumped the town:
 https://github.com/Ixaruz/Luna-Archive-of-Dreams/tree/master/1.6.0/%5BDA-4141-8912-8992%5D%20Mialand/20.11.2020%20%40%2015-40
