### ISSUE TITLE
Dump request :) (DA-9211-0737-7234)

### ISSUE THREAD

**Issue by Lemonlory** [Ixaruz/Luna-Archive-of-Dreams#5]
Hi! I've read you're quite busy with school, but it would be amazing if you could dump this dream (DA-9211-0737-7234). 
Thank you for your great work by the way!

**Comment by Ixaruz** [comment]
heyo, sorry i'm a bit late reading this so i need to update my tool first since 1.7.0 just released. afterwards i'll make sure to dump it :)

**Comment by Lemonlory** [comment]
don't stress yourself! thank you for taking your time.

**Comment by Ixaruz** [comment]
sorry this took way longer than anticipated.

I updated Luna, but also had unique problems with this dream, since I couldn't find where the player's data was located in Ram (turned out I didn't use the right pointer chain, but eh, happens to the best of us).

here's the dump:
https://github.com/Ixaruz/Luna-Archive-of-Dreams/tree/master/1.7.0/%5BDA-9211-0737-7234%5D%20Inochi/15.07.2020%20%40%2018-19

**Comment by Lemonlory** [comment]
Thanks a ton :)

**Comment by Ixaruz** [comment]
No problem :`)
